package model

import (
	"math/rand/v2"
)

var weapons = []string{
	"Blade of Acheron", "Malebolge Scythe", "Styxpiercer", "Infernal Fang", "Hellfire Dagger",
	"Abyssal Reaver", "Flame of Dis", "Geryon's Edge", "Charon’s Oar", "Phlegethon Saber",
	"Wrathbreaker", "Purgatory's Thorn", "Cocytus Shard", "Searing Whip of Minos", "Chains of Cerberus",
	"Vortex of Lethe", "Malacoda’s Cleaver", "Venomous Stinger of the Furies", "Frozen Spear of Caina",
	"Wail of the Damned", "Fiery Sword of Farinata", "Lucifer’s Talon", "Sin Eater’s Blade",
	"Bident of Pluto", "Tornado of Lust", "Pandemonium’s Claw", "Harrowing Lance", "Virgil’s Guiding Rod",
	"Devil’s Kiss", "Shear of Betrayal", "Sword of the Unrepentant", "Alighieri’s Pen",
	"Winged Blade of Geryon", "Tears of the Blasphemer", "Sanguine Fist of the Malebranche",
	"Righteous Flame of St. Lucia", "Spear of the Fallen", "Shackle of Antaeus", "Crescent of the Nine Circles",
	"Horn of Beelzebub", "Fury’s Claw", "Gatekeeper’s Key", "Scourge of Avarice", "Banner of the Crusader",
	"Blade of Despair", "Ashen Pike of the Wrathful", "Serpent’s Tongue of Limbo", "Judicator’s Hammer",
	"Tower of the Heretic", "Warden of the Souls", "Shade's Fang", "Sword of Sodom", "Armor of the Incontinent",
	"Lament of Judas", "Fang of the Tempestuous", "Garrote of the Gluttonous", "Obsidian Halberd of Dis",
	"Specter’s Blade", "Hammer of the Dark Abyss", "Forked Whip of Malice", "Shield of the Holy Inquisition",
	"Virgil’s Scabbard", "Impaler of Brutus", "Viper’s Venom of the Wrathful", "Chains of Contrition",
	"Bloodsoaked Mace of the Seducers", "Lantern of the Treacherous", "Tartaros’ Reach",
	"Crescent Moon of Geryon", "Penance Sword of the Envious", "Sulfurous Edge", "Voice of the Sullen",
	"Stonefist of the Blasphemer", "Glaive of the Furious", "Soulsplitter", "Screech of the Chimeras",
	"Doomseeker", "Oracle’s Wrath", "Inferno Blade of Vengeance", "Firebrand of the Harpies",
	"Devourer of the Lost", "Sickle of the Abysswalker", "Talon of the Damnation", "Cleaver of the Fourth Circle",
	"Voidblade", "Bane of the Heretics", "Breath of the Lamenters", "Aegis of the Righteous",
	"Darkblade of the Seducers", "Phantasmic Edge", "Blackwing Spear of the Malebolge",
	"Claw of the Treacherous", "Sword of the River Acheron", "Infernal Thorn of the Weeping",
	"Judgment Hammer of the Damned", "Bone Spear of the Forgotten", "Flame of the Dark One",
	"Aegis of Purgatory", "Wings of the Fallen", "Stygian Blade", "Soulsunder", "Hellborne Pike",
	"Pitchfork of the Lustful", "Bane of the Wrathful", "Seraphim’s Spear", "The Betrayer's Sword",
	"Dagger of the Ninth Circle", "Spear of the Tormented", "Warden’s Fang", "Howl of the Abyss",
	"Shield of Charon", "Skullcrusher of the Blasphemers", "Gauntlet of the Wicked", "Darkflame",
	"Soulbinder", "Judgment's Edge", "Searing Thorn of Malice", "Chains of Iniquity", "Bloodthorn",
	"Inferno’s Howl", "Brand of the Fallen One", "Pike of the Arrogant", "Bane of Dis", "Brimstone Scythe",
	"Razor of Lucifer", "Crucible of Souls", "Sword of the Deep Abyss", "Demon's Claw", "Heartseeker of Minos",
	"Scepter of Perdition", "Infernal Chains", "Blade of the Sixth Circle", "Wrathfire Spear",
	"Shadow of Beatrice", "Angel’s Wrath", "Serpent’s Whisper", "Iron Brand of the Greedy",
	"Whip of the Seventh Circle", "Blaze of the Fallen Angels", "Demonic Raze", "Searing Chains of Dis",
	"Oblivion's Gaze", "Bident of the Furies", "Lightbane", "Thorn of Treachery", "Hammer of Acheron",
	"Chains of the Abyssal Depths", "Lantern of Virgil", "Spear of Divine Wrath", "Hellspike",
	"Serpent’s Fang of Limbo", "Malebolge Dagger", "Scepter of the Ten Circles", "Soulstealer’s Sword",
	"Armor of the Penitent", "Howl of Alecto", "Scepter of the Weeping", "Cloak of the False Prophet",
	"Abyssfire Blade", "Horn of the Condemned", "Sunderer of Souls", "Brimstone Shield", "Anguishblade",
	"Reaper of Styx", "Inferno's Embrace", "Wailing Fist", "Shackle of the Vicious", "Revenant's Dagger",
	"Chains of Agony", "Seraphim’s Edge", "Torch of Abaddon", "Blade of Judgement", "Blight of the Lost",
	"Redeemer’s Fist", "Pitfall Mace", "Hellfire Pike", "Bane of Cocytus", "Shadow of Malacoda",
	"Flame of the Greedy", "Executioner’s Axe of the Envious", "Chains of the Damned",
	"Bastion of the Crusaders", "Unholy Spear of Vengeance", "Torturer’s Claw", "Thorn of the Ninth Circle",
	"Scourge of the Abyss", "Voice of the Envious", "Whisper of the Tormented", "Spear of Justice",
	"Wrath’s Embrace", "Screech of the Abyssal Birds", "Lament of the Unrepentant", "Inferno’s Whisper",
	"Leviathan’s Fang", "Heart of Avernus", "Malebolge Scepter", "Fist of Anguish", "Darkfire Whip",
	"Aegis of the Fallen", "Rage of the Tempestuous",
}

var helmets = []string{
	"Helm of the Lost", "Helm of the Malebolge", "Helm of Limbo", "Helm of Acheron", "Helm of Perdition",
	"Helm of Minos", "Helm of Stygian Darkness", "Helm of the Fiery Abyss", "Helm of the Crusader",
	"Helm of Cocytus", "Helm of Judgment", "Helm of Eternal Flame", "Helm of Wrath", "Helm of Despair",
	"Helm of Penance", "Helm of Agony", "Helm of Redemption", "Helm of Vengeance", "Helm of the Fallen",
	"Helm of the Abyss", "Helm of the Sullen", "Helm of the Righteous Flame", "Helm of Beelzebub",
	"Helm of Lucifer", "Helm of the Ninth Circle", "Helm of the Malebranche", "Helm of Avarice",
	"Helm of the Tempestuous", "Helm of the Tormented", "Helm of the Furious", "Helm of Treachery",
	"Helm of the Frozen Wastes", "Helm of the Inferno", "Helm of Cerberus", "Helm of the Blasphemer",
	"Helm of Purgatory", "Helm of the Sinners", "Helm of the Unrepentant", "Helm of Sorrow",
	"Helm of the River Styx", "Helm of Dis", "Helm of the Heretic", "Helm of the Abyssal Flames",
	"Helm of Lamentation", "Helm of Torment", "Helm of the Weeping", "Helm of the Damned",
	"Helm of the Betrayer", "Helm of Malice", "Helm of the Defiler", "Helm of the Crusader’s Wrath",
	"Helm of the Raging Storm", "Helm of the Condemned", "Helm of Sisyphus", "Helm of the Inquisitor",
	"Helm of the Infernal King", "Helm of the Chained Souls", "Helm of the Deceiver", "Helm of False Hope",
	"Helm of Blackened Ash", "Helm of Eternal Flames", "Helm of the Ashen Wastes", "Helm of the Drowned Souls",
	"Helm of the Tempest", "Helm of Eternal Penance", "Helm of Fiendish Shadows", "Helm of Divine Wrath",
	"Helm of Endless Agony", "Helm of the Tainted Spirits", "Helm of the Relentless Fury",
	"Helm of the Hollow Heart", "Helm of Envy", "Helm of the Broken Faith", "Helm of the Fallen Angels",
	"Helm of the Abyssal Truth", "Helm of Judgment's Hand", "Helm of the Righteous Path",
	"Helm of the Infernal Judge", "Helm of Burning Regret", "Helm of the Forsaken", "Helm of Burning Chains",
	"Helm of the Blasphemous", "Helm of the Silent Sorrow", "Helm of the Sin Bearer", "Helm of the Damned Souls",
	"Helm of the Banished", "Helm of Chains", "Helm of Infernal Flames", "Helm of Dark Retribution",
	"Helm of the Abyssal Gaze", "Helm of Divine Punishment", "Helm of Eternal Suffering",
	"Helm of the Void's Grasp", "Helm of the Cursed", "Helm of Blighted Souls", "Helm of Eternal Darkness",
	"Helm of Fallen Grace", "Helm of Sinful Memories", "Helm of Infernal Anguish", "Helm of the Vile Fiend",
	"Helm of Infernal Woe", "Helm of the Hellscream", "Helm of Merciless Flames", "Helm of the Burning Spire",
	"Helm of Desolate Skies", "Helm of the Corrupted", "Helm of Eternal Flames", "Helm of Weeping Souls",
	"Helm of Eternal Vengeance", "Helm of the Shadow Lords", "Helm of Twisted Fates", "Helm of the Forsaken Souls",
	"Helm of the Abyssal Forge", "Helm of the Void", "Helm of Death's Whisper", "Helm of the Forsaken Spirits",
	"Helm of the Endless Pit", "Helm of the Writhing Shadows", "Helm of Fiery Judgment", "Helm of Wrathful Flame",
	"Helm of the Pit's Roar", "Helm of Fiery Condemnation", "Helm of Wrath's Touch", "Helm of the Ashen Lord",
	"Helm of Dark Confessions", "Helm of the Weeping Flame", "Helm of the Abyssal Tide", "Helm of the Damned Flame",
	"Helm of Infernal Winds", "Helm of the Burning Abyss", "Helm of the Eternal Watcher",
	"Helm of Smoldering Skies", "Helm of the Abyssal Lord", "Helm of Despair's Embrace",
	"Helm of Darkened Flames", "Helm of the Infernal Heart", "Helm of Righteous Fury",
	"Helm of the Cursed Crusader", "Helm of Agony’s Embrace", "Helm of the Forsaken Ones",
	"Helm of Burning Fate", "Helm of Tormented Souls", "Helm of the Defiler’s Hand",
	"Helm of the Abyssal Guardian", "Helm of Corrupted Souls", "Helm of Endless Wrath",
	"Helm of the Pit's Guardian", "Helm of the Weeping Void", "Helm of the Sinful Flame",
	"Helm of the Blackened Flame", "Helm of Infernal Purity", "Helm of the Abyssal Ward",
	"Helm of the Twisting Fate", "Helm of Shattered Dreams", "Helm of the Sinless Ones",
	"Helm of the Cursed Path", "Helm of Eternal Shadows", "Helm of Malicious Flames",
	"Helm of Infernal Betrayal", "Helm of the Abyssal Scream", "Helm of the Void's Edge",
	"Helm of Forsaken Light", "Helm of the Damned Judgment", "Helm of Eternal Regret",
	"Helm of the Silent Abyss", "Helm of the Abyssal Fury", "Helm of Sinner's Wrath", "Helm of the Cursed Abyss",
	"Helm of Raging Tempests", "Helm of Eternal Misery", "Helm of the Burning Void", "Helm of the Void Keeper",
	"Helm of the Infernal Guardian", "Helm of the Fiend's Eye", "Helm of the Banished Lord", "Helm of Wretched Souls",
	"Helm of the Abyssal Hunger", "Helm of the Eternal Flames", "Helm of Lost Souls", "Helm of the Crimson Flame",
	"Helm of the Cursed Fiend", "Helm of Smoldering Regret", "Helm of the Infernal Beast", "Helm of the Void Reaver",
	"Helm of the Abyssal Flame", "Helm of the Eternal Watch", "Helm of the Burning Wrath", "Helm of the Void’s Tear",
	"Helm of Shattered Souls", "Helm of Blighted Flames", "Helm of the Forsaken Flames", "Helm of Abyssal Anguish",
	"Helm of Dark Forgiveness", "Helm of Lost Hope", "Helm of the Abyssal Flame", "Helm of Unyielding Wrath",
	"Helm of Eternal Flames", "Helm of Infernal Hope", "Helm of the Ashen Abyss", "Helm of the Abyssal Echo",
	"Helm of Fiendish Flames", "Helm of the Abyssal Judge", "Helm of Smoldering Anguish", "Helm of the Infernal Tide",
	"Helm of the Cursed Flame", "Helm of Abyssal Despair", "Helm of the Tormented",
}

var chestPlates = []string{
	"Breastplate of Wrath", "Chestplate of the Treacherous", "Armor of the Blasphemer", "Breastplate of Avarice",
	"Chestplate of Damnation", "Breastplate of Eternal Punishment", "Chestplate of Lucifer’s Flame",
	"Breastplate of Souls", "Chestplate of the Abyss", "Breastplate of the Lost", "Chestplate of the Fallen",
	"Chestplate of the Righteous Flame", "Chestplate of Redemption", "Breastplate of Agony",
	"Breastplate of Vengeance", "Armor of the Weeping", "Armor of Eternal Judgment", "Armor of the Tempest",
	"Armor of the Furies", "Breastplate of the Furies", "Chestplate of the Damned", "Armor of Envy",
	"Chestplate of Despair", "Breastplate of Perdition", "Armor of the Abyss", "Chestplate of the Frozen",
	"Breastplate of the Sinful", "Chestplate of Eternal Regret", "Breastplate of the Blighted",
	"Chestplate of the Damned Souls", "Chestplate of the Fallen Angels", "Breastplate of Malice",
	"Armor of the Betrayer", "Chestplate of the Tormented", "Chestplate of the Forsaken",
	"Chestplate of Unholy Fire", "Chestplate of the Weeping Souls", "Breastplate of the Hollow",
	"Chestplate of the Abyssal Guardian", "Breastplate of the Cursed", "Chestplate of the Fiery Abyss",
	"Armor of the Fallen", "Breastplate of the Corrupted", "Chestplate of Eternal Suffering",
	"Breastplate of the Sin Bearer", "Chestplate of the Lost Souls", "Armor of Dark Retribution",
	"Chestplate of the Infernal King", "Chestplate of the Unrepentant", "Breastplate of the Forsaken",
	"Armor of the Shadows", "Chestplate of the Wretched", "Chestplate of the Hellspawn",
	"Armor of the Sinful Ones", "Chestplate of the Unyielding", "Chestplate of the Ashen",
	"Chestplate of the Desolate", "Breastplate of the Shadow", "Breastplate of the Forsaken Hope",
	"Chestplate of Sinister Dreams", "Armor of Unholy Judgment", "Chestplate of Tormented Souls",
	"Chestplate of the Abyssal Fire", "Armor of Infernal Wrath", "Chestplate of Eternal Flame",
	"Chestplate of the Tainted", "Chestplate of the Fallen King", "Breastplate of the Eternal Night",
	"Armor of the Blighted Souls", "Chestplate of Dark Despair", "Breastplate of the Cursed Ones",
	"Chestplate of the Fiendish", "Armor of the Darkened Heart", "Chestplate of the Infernal",
	"Chestplate of the Sorrowful", "Breastplate of the Relentless", "Chestplate of Endless Pain",
	"Armor of the Forsaken Light", "Breastplate of the Eternal Gloom", "Chestplate of Lost Dreams",
	"Armor of the Infernal Heart", "Chestplate of the Vengeful", "Chestplate of the Fiery Flame",
	"Breastplate of the Darkened", "Armor of Eternal Shadows", "Chestplate of the Hollow Heart",
	"Chestplate of the Forgotten", "Breastplate of the Drowned", "Armor of Unending Torment",
	"Chestplate of the Dread", "Chestplate of the Ashen Guardian", "Armor of the Weeping",
	"Breastplate of Infernal Shadows", "Chestplate of the Infernal Flame", "Breastplate of the Dark Ones",
	"Chestplate of Sorrow's Embrace", "Armor of the Fallen Souls", "Chestplate of the Scorned",
	"Armor of Sinister Fates", "Chestplate of the Eternal Watch", "Breastplate of the Cursed Heart",
	"Armor of the Eternal Night", "Chestplate of the Abyssal Tide", "Chestplate of the Darkened Path",
	"Breastplate of Fiery Judgment", "Armor of the Forsaken Abyss", "Chestplate of the Damned King",
	"Chestplate of Eternal Regret", "Breastplate of the Abyssal Wrath", "Armor of the Forsaken Wastes",
	"Chestplate of the Cursed King", "Chestplate of the Righteous Fury", "Breastplate of the Twisted",
	"Armor of Eternal Nightmares", "Chestplate of the Cursed Flame", "Chestplate of the Silent Scream",
	"Breastplate of the Eternal Guardian", "Armor of the Shadowed Ones", "Chestplate of the Infernal Judge",
	"Chestplate of the Malicious", "Breastplate of Eternal Darkness", "Chestplate of the Cursed Abyss",
	"Armor of the Vengeful", "Chestplate of the Forsaken Guardian", "Chestplate of the Lost Flame",
	"Breastplate of Unholy Hope", "Armor of the Abyssal Guardian", "Chestplate of the Forsaken Abyss",
	"Chestplate of the Blighted Heart", "Armor of the Forgotten", "Breastplate of the Silent Ones",
	"Chestplate of the Tormented Flames", "Armor of the Ashen King", "Chestplate of the Infernal Wastes",
	"Chestplate of the Unholy", "Breastplate of the Unrepentant King", "Armor of Dark Anguish",
	"Chestplate of the Infernal Abyss", "Breastplate of the Forsaken Fate", "Chestplate of the Abyssal Judge",
	"Armor of the Vengeful Spirits", "Chestplate of the Forsaken Shadows", "Breastplate of the Wrathful",
	"Chestplate of the Weeping Abyss", "Armor of the Blasphemer", "Chestplate of the Eternal Flames",
	"Chestplate of the Drowned Souls", "Breastplate of the Damned Judgment", "Chestplate of the Ashen Lord",
	"Armor of the Forsaken Fire", "Chestplate of the Eternal Watcher", "Breastplate of the Fallen Guardian",
	"Chestplate of the Infernal Guardian", "Armor of the Abyssal Flame", "Chestplate of the Eternal Woe",
	"Chestplate of the Damned Flame", "Breastplate of the Silent Fury", "Armor of the Corrupted Heart",
	"Chestplate of the Cursed Spirits", "Breastplate of the Abyssal Reaver", "Chestplate of the Infernal Hand",
	"Armor of the Unyielding", "Chestplate of the Fiery Abyss", "Chestplate of the Sinful Ones",
	"Breastplate of the Fallen Flame", "Chestplate of the Forsaken Embrace", "Armor of Dark Regret",
	"Chestplate of the Abyssal Shadows", "Chestplate of the Weeping Fire", "Breastplate of the Cursed One",
	"Armor of the Forgotten Souls", "Chestplate of the Eternal Ashes", "Chestplate of the Damned Heart",
	"Breastplate of the Abyssal Embrace", "Chestplate of the Darkened Guardian", "Armor of the Fiery Void",
	"Chestplate of the Infernal Souls", "Chestplate of the Ashen Sorrow", "Breastplate of the Forsaken One",
	"Armor of the Silent Abyss", "Chestplate of the Vengeful Flame", "Chestplate of the Forsaken Wrath",
	"Breastplate of the Unyielding Shadows", "Chestplate of the Abyssal Scorn", "Armor of the Relentless",
	"Chestplate of the Unholy Night", "Chestplate of the Wailing Souls", "Breastplate of the Forsaken Night",
	"Armor of the Cursed Watcher", "Chestplate of the Eternal Reaver", "Chestplate of the Abyssal Keeper",
	"Breastplate of the Darkened One", "Chestplate of the Forsaken Blight", "Armor of the Wretched",
	"Chestplate of the Infernal Fire", "Chestplate of the Ashen Guardian", "Breastplate of the Vengeful Watch",
	"Armor of the Sinful Flame", "Chestplate of the Abyssal Vengeance", "Chestplate of the Forsaken Anguish",
	"Breastplate of the Damned Soul", "Chestplate of the Silent Woe", "Armor of the Forsaken Tempest",
	"Chestplate of the Cursed Flame", "Chestplate of the Abyssal Storm", "Breastplate of the Eternal Watcher",
	"Armor of the Abyssal Void", "Chestplate of the Forsaken Fury", "Chestplate of the Drowned Guardian",
	"Breastplate of the Forsaken Shadows", "Armor of the Eternal Wail", "Chestplate of the Cursed Guardian",
	"Chestplate of the Sinful Shadows", "Breastplate of the Abyssal Tyrant", "Chestplate of the Eternal Abyss",
	"Armor of the Forsaken King",
}

var greaves = []string{
	"Greaves of the Damned", "Leggings of the Forsaken", "Greaves of the Infernal", "Greaves of the Abyss",
	"Leggings of Wrath", "Greaves of Eternal Agony", "Greaves of the Fallen", "Leggings of the Abyssal King",
	"Greaves of the Weeping Souls", "Leggings of Malice", "Greaves of Perdition", "Leggings of the Wretched",
	"Greaves of the Blighted", "Leggings of the Cursed", "Greaves of the Darkened", "Leggings of the Lost",
	"Greaves of Fiery Judgment", "Leggings of the Vengeful", "Greaves of the Righteous", "Leggings of the Damned",
	"Greaves of the Abyssal Flame", "Leggings of the Infernal Flame", "Greaves of the Forsaken King",
	"Leggings of the Cursed Guardian", "Greaves of the Eternal Watch", "Leggings of the Sin Bearer",
	"Greaves of the Abyssal Guardian", "Leggings of the Weeping", "Greaves of the Eternal Night",
	"Leggings of the Blasphemer", "Greaves of the Forsaken Souls", "Leggings of Eternal Wrath",
	"Greaves of the Shadowed", "Leggings of the Darkened Heart", "Greaves of the Infernal Wastes",
	"Leggings of Eternal Suffering", "Greaves of the Unrepentant", "Leggings of the Fiery Abyss",
	"Greaves of the Eternal Flame", "Leggings of the Cursed Abyss", "Greaves of the Forsaken Fate",
	"Leggings of the Abyssal Fury", "Greaves of the Silent Ones", "Leggings of Dark Despair",
	"Greaves of the Fallen Angels", "Leggings of the Forsaken Night", "Greaves of the Eternal Shadows",
	"Leggings of the Abyssal Tide", "Greaves of the Cursed King", "Leggings of the Ashen Guardian",
	"Greaves of the Damned Soul", "Leggings of the Forsaken Fury", "Greaves of the Vengeful Fire",
	"Leggings of the Cursed Flame", "Greaves of the Abyssal Reaver", "Leggings of the Infernal Beast",
	"Greaves of the Blighted Heart", "Leggings of the Weeping Flame", "Greaves of Eternal Nightmares",
	"Leggings of Sinister Fates", "Greaves of the Corrupted", "Leggings of the Forsaken Spirits",
	"Greaves of the Ashen Flame", "Leggings of the Darkened Path", "Greaves of the Fallen Ones",
	"Leggings of the Silent Abyss", "Greaves of the Forsaken Guardian", "Leggings of the Sinful Ones",
	"Greaves of the Eternal Abyss", "Leggings of the Darkened One", "Greaves of the Abyssal Watch",
	"Leggings of the Infernal Heart", "Greaves of the Tormented", "Leggings of the Vengeful Wrath",
	"Greaves of the Forsaken Tempest", "Leggings of the Silent Guardian", "Greaves of the Cursed Fire",
	"Leggings of the Abyssal Vengeance", "Greaves of the Damned Flame", "Leggings of the Eternal Gloom",
	"Greaves of the Infernal Judge", "Leggings of the Weeping Abyss", "Greaves of the Corrupted Heart",
	"Leggings of the Unholy", "Greaves of the Cursed Watcher", "Leggings of the Forsaken Fate",
	"Greaves of the Eternal Scorn", "Leggings of the Abyssal Shadow", "Greaves of the Dread",
	"Leggings of the Silent Sorrow", "Greaves of the Ashen Wastes", "Leggings of the Wretched King",
	"Greaves of the Infernal Void", "Leggings of the Fallen Lord", "Greaves of the Forsaken One",
	"Leggings of the Abyssal Void", "Greaves of the Fiendish", "Leggings of the Eternal Watcher",
	"Greaves of the Sinister", "Leggings of the Abyssal Storm", "Greaves of the Forsaken Embrace",
	"Leggings of the Darkened Soul", "Greaves of the Eternal Flame", "Leggings of the Infernal Guardian",
	"Greaves of the Silent Flame", "Leggings of the Forsaken Shadows", "Greaves of the Abyssal Keeper",
	"Leggings of the Cursed Embrace", "Greaves of the Eternal Ashes", "Leggings of the Infernal Watch",
	"Greaves of the Lost Dreams", "Leggings of the Darkened Fury", "Greaves of the Ashen King",
	"Leggings of the Forsaken Light", "Greaves of the Silent Woe", "Leggings of the Blighted Souls",
	"Greaves of the Infernal Tide", "Leggings of the Damned Watch", "Greaves of the Abyssal Heart",
	"Leggings of the Forsaken Guardian", "Greaves of the Vengeful King", "Leggings of the Unholy Fury",
	"Greaves of the Silent Abyss", "Leggings of the Cursed Guardian", "Greaves of the Eternal Wrath",
	"Leggings of the Forsaken Tyrant", "Greaves of the Abyssal Echo", "Leggings of the Infernal Judge",
	"Greaves of the Damned Soul", "Leggings of the Darkened Shadows", "Greaves of the Blighted Guardian",
	"Leggings of the Weeping Souls", "Greaves of the Forsaken Wastes", "Leggings of the Vengeful Watch",
	"Greaves of the Abyssal Night", "Leggings of the Silent Guardian", "Greaves of the Infernal Darkness",
	"Leggings of the Forsaken Scorn", "Greaves of the Eternal Sorrow", "Leggings of the Damned Night",
	"Greaves of the Abyssal Flame", "Leggings of the Forsaken Reaver", "Greaves of the Silent Tempest",
	"Leggings of the Cursed Watch", "Greaves of the Eternal Night", "Leggings of the Blasphemer",
	"Greaves of the Darkened Watcher", "Leggings of the Forsaken Guardian", "Greaves of the Damned Tyrant",
	"Leggings of the Abyssal Reaver", "Greaves of the Infernal Tide", "Leggings of the Eternal Scorn",
	"Greaves of the Darkened Abyss", "Leggings of the Silent Fury", "Greaves of the Cursed Flame",
	"Leggings of the Weeping Guardian", "Greaves of the Forsaken King", "Leggings of the Abyssal Wrath",
	"Greaves of the Infernal Night", "Leggings of the Damned Souls", "Greaves of the Eternal Reaver",
	"Leggings of the Abyssal Fire", "Greaves of the Forsaken Shadow", "Leggings of the Cursed Spirit",
	"Greaves of the Darkened Wastes", "Leggings of the Silent Embrace", "Greaves of the Vengeful Flames",
	"Leggings of the Cursed Abyss", "Greaves of the Forsaken Watch", "Leggings of the Eternal Guardian",
	"Greaves of the Abyssal Fury", "Leggings of the Silent Heart", "Greaves of the Infernal Scorn",
	"Leggings of the Forsaken Guardian", "Greaves of the Eternal Night", "Leggings of the Blighted Flame",
	"Greaves of the Abyssal Shadow", "Leggings of the Damned Guardian", "Greaves of the Forsaken Abyss",
	"Leggings of the Silent Guardian", "Greaves of the Infernal Woe", "Leggings of the Eternal Flame",
	"Greaves of the Darkened Fury", "Leggings of the Forsaken One", "Greaves of the Cursed Abyss",
	"Leggings of the Abyssal Void", "Greaves of the Forsaken Guardian", "Leggings of the Vengeful King",
	"Greaves of the Silent Guardian", "Leggings of the Damned Fate", "Greaves of the Infernal Flame",
	"Leggings of the Forsaken King", "Greaves of the Abyssal Fire", "Leggings of the Cursed Shadow",
	"Greaves of the Eternal Watch", "Leggings of the Blighted Guardian", "Greaves of the Damned Soul",
	"Leggings of the Forsaken Fury", "Greaves of the Abyssal Wrath", "Leggings of the Silent Tempest",
	"Greaves of the Infernal Darkness", "Leggings of the Forsaken Night", "Greaves of the Eternal Scorn",
	"Leggings of the Cursed Fire", "Greaves of the Abyssal Watch", "Leggings of the Forsaken Guardian",
	"Greaves of the Vengeful Shadow", "Leggings of the Damned Flame", "Greaves of the Silent Abyss",
	"Leggings of the Darkened Wastes", "Greaves of the Infernal Tyrant", "Leggings of the Abyssal King",
	"Greaves of the Eternal Shadow", "Leggings of the Forsaken Guardian", "Greaves of the Weeping Flame",
	"Leggings of the Cursed Abyss",
}

var vambraces = []string{
	"Vambraces of the Abyss", "Bracers of the Damned", "Vambraces of the Forsaken", "Bracers of the Infernal",
	"Vambraces of Eternal Wrath", "Bracers of the Blighted", "Vambraces of Perdition", "Bracers of the Wretched",
	"Vambraces of the Cursed", "Bracers of the Weeping Souls", "Vambraces of the Lost", "Bracers of Malice",
	"Vambraces of the Ashen", "Bracers of the Eternal Night", "Vambraces of the Unholy", "Bracers of the Abyssal King",
	"Vambraces of the Fallen", "Bracers of the Vengeful", "Vambraces of the Darkened", "Bracers of Sinister Dreams",
	"Vambraces of the Forsaken Guardian", "Bracers of Fiery Judgment", "Vambraces of the Infernal Flames",
	"Bracers of the Silent Ones", "Vambraces of the Eternal Shadows", "Bracers of the Damned Souls",
	"Vambraces of the Forsaken Hope", "Bracers of the Eternal Woe", "Vambraces of the Abyssal Fury",
	"Bracers of the Darkened Heart", "Vambraces of the Cursed Flame", "Bracers of the Infernal Watch",
	"Vambraces of the Silent Woe", "Bracers of the Forsaken Night", "Vambraces of the Vengeful Fire",
	"Bracers of the Eternal Guardian", "Vambraces of the Abyssal Reaver", "Bracers of the Fallen Angels",
	"Vambraces of the Cursed Spirits", "Bracers of the Unrepentant", "Vambraces of the Forsaken Tempest",
	"Bracers of the Ashen Wastes", "Vambraces of Dark Despair", "Bracers of the Damned King",
	"Vambraces of the Silent Fury", "Bracers of the Cursed Watcher", "Vambraces of the Eternal Flame",
	"Bracers of the Forsaken Shadows", "Vambraces of the Abyssal Watch", "Bracers of the Infernal Judge",
	"Vambraces of the Darkened Fury", "Bracers of the Eternal Reaver", "Vambraces of the Blighted Heart",
	"Bracers of the Silent Abyss", "Vambraces of the Forsaken Woe", "Bracers of the Cursed Guardian",
	"Vambraces of the Abyssal Guardian", "Bracers of the Fiery Abyss", "Vambraces of the Weeping Guardian",
	"Bracers of the Eternal Night", "Vambraces of the Forsaken King", "Bracers of the Infernal Beast",
	"Vambraces of the Lost Souls", "Bracers of the Vengeful Shadows", "Vambraces of the Cursed Night",
	"Bracers of the Eternal Scorn", "Vambraces of the Abyssal Void", "Bracers of the Forsaken Echo",
	"Vambraces of the Infernal Storm", "Bracers of the Darkened Path", "Vambraces of the Silent Guardian",
	"Bracers of the Forsaken Watch", "Vambraces of the Ashen Guardian", "Bracers of the Damned Flame",
	"Vambraces of the Eternal Guardian", "Bracers of the Abyssal Embrace", "Vambraces of the Cursed King",
	"Bracers of the Fallen Lord", "Vambraces of the Darkened King", "Bracers of the Forsaken Fury",
	"Vambraces of the Eternal Woe", "Bracers of the Abyssal Nightmare", "Vambraces of the Silent One",
	"Bracers of the Damned Guardian", "Vambraces of the Forsaken Watcher", "Bracers of the Darkened Souls",
	"Vambraces of the Vengeful Abyss", "Bracers of the Eternal Wrath", "Vambraces of the Infernal Heart",
	"Bracers of the Cursed Shadows", "Vambraces of the Forsaken Watch", "Bracers of the Abyssal Keeper",
	"Vambraces of the Silent Tempest", "Bracers of the Damned Echo", "Vambraces of the Forsaken Flame",
	"Bracers of the Darkened Soul", "Vambraces of the Eternal Night", "Bracers of the Abyssal Shadows",
	"Vambraces of the Infernal Watch", "Bracers of the Weeping Souls", "Vambraces of the Forsaken King",
	"Bracers of the Damned King", "Vambraces of the Silent Guardian", "Bracers of the Eternal Flame",
	"Vambraces of the Abyssal Wrath", "Bracers of the Cursed Fate", "Vambraces of the Forsaken Tempest",
	"Bracers of the Darkened Heart", "Vambraces of the Eternal Guardian", "Bracers of the Abyssal Fury",
	"Vambraces of the Infernal Nightmare", "Bracers of the Lost Guardian", "Vambraces of the Forsaken Wastes",
	"Bracers of the Weeping Abyss", "Vambraces of the Cursed Spirits", "Bracers of the Eternal Ashes",
	"Vambraces of the Abyssal Flame", "Bracers of the Forsaken Guardian", "Vambraces of the Damned Fury",
	"Bracers of the Silent Flame", "Vambraces of the Infernal Embrace", "Bracers of the Abyssal Shadow",
	"Vambraces of the Cursed Watcher", "Bracers of the Eternal Night", "Vambraces of the Forsaken Watch",
	"Bracers of the Darkened King", "Vambraces of the Vengeful King", "Bracers of the Damned Fate",
	"Vambraces of the Silent Abyss", "Bracers of the Eternal Guardian", "Vambraces of the Abyssal Wrath",
	"Bracers of the Forsaken Flame", "Vambraces of the Darkened Guardian", "Bracers of the Infernal Fire",
	"Vambraces of the Cursed Night", "Bracers of the Eternal Scorn", "Vambraces of the Forsaken Wastes",
	"Bracers of the Damned Flame", "Vambraces of the Silent Shadows", "Bracers of the Abyssal Night",
	"Vambraces of the Vengeful Watch", "Bracers of the Eternal Watcher", "Vambraces of the Forsaken Tempest",
	"Bracers of the Infernal Guardian", "Vambraces of the Darkened Flame", "Bracers of the Damned Woe",
	"Vambraces of the Silent Fury", "Bracers of the Abyssal Guardian", "Vambraces of the Forsaken Night",
	"Bracers of the Cursed Heart", "Vambraces of the Eternal Ashes", "Bracers of the Darkened Soul",
	"Vambraces of the Lost King", "Bracers of the Forsaken Guardian", "Vambraces of the Abyssal Fury",
	"Bracers of the Infernal Watch", "Vambraces of the Cursed Spirit", "Bracers of the Eternal Night",
	"Vambraces of the Forsaken Guardian", "Bracers of the Darkened Fury", "Vambraces of the Silent Abyss",
	"Bracers of the Damned Flame", "Vambraces of the Forsaken Woe", "Bracers of the Abyssal Keeper",
	"Vambraces of the Eternal Guardian", "Bracers of the Cursed Shadows", "Vambraces of the Lost Guardian",
	"Bracers of the Silent Fury", "Vambraces of the Infernal Tyrant", "Bracers of the Abyssal Reaver",
	"Vambraces of the Forsaken Shadow", "Bracers of the Darkened Abyss", "Vambraces of the Eternal Night",
	"Bracers of the Silent One", "Vambraces of the Infernal Flames", "Bracers of the Forsaken Wastes",
	"Vambraces of the Abyssal Storm", "Bracers of the Darkened Path", "Vambraces of the Eternal Wrath",
	"Bracers of the Forsaken Fate", "Vambraces of the Damned Echo", "Bracers of the Abyssal Watch",
	"Vambraces of the Silent Watcher", "Bracers of the Cursed Abyss", "Vambraces of the Infernal Guardian",
	"Bracers of the Forsaken Guardian",
}

var gloves = []string{
	"Gloves of the Abyss", "Fingers of the Damned", "Gloves of the Forsaken", "Fingers of the Infernal",
	"Gloves of Eternal Wrath", "Fingers of the Blighted", "Gloves of Perdition", "Fingers of the Wretched",
	"Gloves of the Cursed", "Fingers of the Weeping Souls", "Gloves of the Lost", "Fingers of Malice",
	"Gloves of the Ashen", "Fingers of the Eternal Night", "Gloves of the Unholy", "Fingers of the Abyssal King",
	"Gloves of the Fallen", "Fingers of the Vengeful", "Gloves of the Darkened", "Fingers of Sinister Dreams",
	"Gloves of the Forsaken Guardian", "Fingers of Fiery Judgment", "Gloves of the Infernal Flames",
	"Fingers of the Silent Ones", "Gloves of the Eternal Shadows", "Fingers of the Damned Souls",
	"Gloves of the Forsaken Hope", "Fingers of the Eternal Woe", "Gloves of the Abyssal Fury",
	"Fingers of the Darkened Heart", "Gloves of the Cursed Flame", "Fingers of the Infernal Watch",
	"Gloves of the Silent Woe", "Fingers of the Forsaken Night", "Gloves of the Vengeful Fire",
	"Fingers of the Eternal Guardian", "Gloves of the Abyssal Reaver", "Fingers of the Fallen Angels",
	"Gloves of the Cursed Spirits", "Fingers of the Unrepentant", "Gloves of the Forsaken Tempest",
	"Fingers of the Ashen Wastes", "Gloves of Dark Despair", "Fingers of the Damned King",
	"Gloves of the Silent Fury", "Fingers of the Cursed Watcher", "Gloves of the Eternal Flame",
	"Fingers of the Forsaken Shadows", "Gloves of the Abyssal Watch", "Fingers of the Infernal Judge",
	"Gloves of the Darkened Fury", "Fingers of the Eternal Reaver", "Gloves of the Blighted Heart",
	"Fingers of the Silent Abyss", "Gloves of the Forsaken Woe", "Fingers of the Cursed Guardian",
	"Gloves of the Abyssal Guardian", "Fingers of the Fiery Abyss", "Gloves of the Weeping Guardian",
	"Fingers of the Eternal Night", "Gloves of the Forsaken King", "Fingers of the Infernal Beast",
	"Gloves of the Lost Souls", "Fingers of the Vengeful Shadows", "Gloves of the Cursed Night",
	"Fingers of the Eternal Scorn", "Gloves of the Abyssal Void", "Fingers of the Forsaken Echo",
	"Gloves of the Infernal Storm", "Fingers of the Darkened Path", "Gloves of the Silent Guardian",
	"Fingers of the Forsaken Watch", "Gloves of the Ashen Guardian", "Fingers of the Damned Flame",
	"Gloves of the Eternal Guardian", "Fingers of the Abyssal Embrace", "Gloves of the Cursed King",
	"Fingers of the Fallen Lord", "Gloves of the Darkened King", "Fingers of the Forsaken Fury",
	"Gloves of the Eternal Woe", "Fingers of the Abyssal Nightmare", "Gloves of the Silent One",
	"Gloves of the Damned Guardian", "Fingers of the Forsaken Watcher", "Gloves of the Darkened Souls",
	"Fingers of the Vengeful Abyss", "Gloves of the Eternal Wrath", "Fingers of the Infernal Heart",
	"Gloves of the Cursed Shadows", "Fingers of the Forsaken Watch", "Gloves of the Abyssal Keeper",
	"Fingers of the Silent Tempest", "Gloves of the Damned Echo", "Fingers of the Forsaken Flame",
	"Gloves of the Darkened Soul", "Fingers of the Eternal Night", "Gloves of the Abyssal Shadows",
	"Gloves of the Infernal Watch", "Fingers of the Weeping Souls", "Gloves of the Forsaken King",
	"Fingers of the Damned King", "Gloves of the Silent Guardian", "Fingers of the Eternal Flame",
	"Gloves of the Abyssal Wrath", "Fingers of the Cursed Fate", "Gloves of the Forsaken Tempest",
	"Fingers of the Darkened Heart", "Gloves of the Eternal Guardian", "Fingers of the Abyssal Fury",
	"Gloves of the Infernal Nightmare", "Fingers of the Lost Guardian", "Gloves of the Forsaken Wastes",
	"Fingers of the Weeping Abyss", "Gloves of the Cursed Spirits", "Fingers of the Eternal Ashes",
	"Gloves of the Abyssal Flame", "Fingers of the Forsaken Guardian", "Gloves of the Damned Fury",
	"Fingers of the Silent Flame", "Gloves of the Infernal Embrace", "Fingers of the Abyssal Shadow",
	"Gloves of the Cursed Watcher", "Fingers of the Eternal Night", "Gloves of the Forsaken Watch",
	"Fingers of the Darkened King", "Gloves of the Vengeful King", "Fingers of the Damned Fate",
	"Gloves of the Silent Abyss", "Fingers of the Eternal Guardian", "Gloves of the Abyssal Wrath",
	"Fingers of the Forsaken Flame", "Gloves of the Darkened Guardian", "Fingers of the Infernal Fire",
	"Gloves of the Cursed Night", "Fingers of the Eternal Scorn", "Gloves of the Forsaken Wastes",
	"Fingers of the Damned Flame", "Gloves of the Silent Shadows", "Fingers of the Abyssal Night",
	"Gloves of the Vengeful Watch", "Fingers of the Eternal Watcher", "Gloves of the Forsaken Tempest",
	"Fingers of the Infernal Guardian", "Gloves of the Darkened Flame", "Fingers of the Damned Woe",
	"Gloves of the Silent Fury", "Fingers of the Abyssal Guardian", "Gloves of the Forsaken Night",
	"Fingers of the Cursed Heart", "Gloves of the Eternal Ashes", "Fingers of the Darkened Soul",
	"Gloves of the Lost King", "Fingers of the Forsaken Guardian", "Gloves of the Abyssal Fury",
	"Fingers of the Infernal Watch", "Gloves of the Cursed Spirit", "Fingers of the Eternal Night",
	"Gloves of the Forsaken Guardian", "Fingers of the Darkened Fury", "Gloves of the Silent Abyss",
	"Fingers of the Damned Flame", "Gloves of the Forsaken Woe", "Fingers of the Abyssal Keeper",
	"Gloves of the Eternal Guardian", "Fingers of the Cursed Shadows", "Gloves of the Lost Guardian",
	"Fingers of the Silent Fury", "Gloves of the Infernal Tyrant", "Fingers of the Abyssal Reaver",
	"Gloves of the Forsaken Shadow", "Fingers of the Darkened Abyss", "Gloves of the Eternal Night",
	"Fingers of the Silent One", "Gloves of the Infernal Flames", "Fingers of the Forsaken Wastes",
	"Gloves of the Abyssal Storm", "Fingers of the Darkened Path", "Gloves of the Eternal Wrath",
	"Fingers of the Forsaken Fate", "Gloves of the Damned Echo", "Fingers of the Abyssal Watch",
	"Gloves of the Silent Watcher", "Fingers of the Cursed Abyss", "Gloves of the Infernal Guardian",
	"Fingers of the Forsaken Guardian",
}

var boots = []string{
	"Boots of the Abyss", "Footfalls of the Damned", "Boots of the Forsaken", "Footfalls of the Infernal",
	"Boots of Eternal Wrath", "Footfalls of the Blighted", "Boots of Perdition", "Footfalls of the Wretched",
	"Boots of the Cursed", "Footfalls of the Weeping Souls", "Boots of the Lost", "Footfalls of Malice",
	"Boots of the Ashen", "Footfalls of the Eternal Night", "Boots of the Unholy", "Footfalls of the Abyssal King",
	"Boots of the Fallen", "Footfalls of the Vengeful", "Boots of the Darkened", "Footfalls of Sinister Dreams",
	"Boots of the Forsaken Guardian", "Footfalls of Fiery Judgment", "Boots of the Infernal Flames",
	"Footfalls of the Silent Ones", "Boots of the Eternal Shadows", "Footfalls of the Damned Souls",
	"Boots of the Forsaken Hope", "Footfalls of the Eternal Woe", "Boots of the Abyssal Fury",
	"Footfalls of the Darkened Heart", "Boots of the Cursed Flame", "Footfalls of the Infernal Watch",
	"Boots of the Silent Woe", "Footfalls of the Forsaken Night", "Boots of the Vengeful Fire",
	"Footfalls of the Eternal Guardian", "Boots of the Abyssal Reaver", "Footfalls of the Fallen Angels",
	"Boots of the Cursed Spirits", "Footfalls of the Unrepentant", "Boots of the Forsaken Tempest",
	"Footfalls of the Ashen Wastes", "Boots of Dark Despair", "Footfalls of the Damned King",
	"Boots of the Silent Fury", "Footfalls of the Cursed Watcher", "Boots of the Eternal Flame",
	"Footfalls of the Forsaken Shadows", "Boots of the Abyssal Watch", "Footfalls of the Infernal Judge",
	"Boots of the Darkened Fury", "Footfalls of the Eternal Reaver", "Boots of the Blighted Heart",
	"Footfalls of the Silent Abyss", "Boots of the Forsaken Woe", "Footfalls of the Cursed Guardian",
	"Boots of the Abyssal Guardian", "Footfalls of the Fiery Abyss", "Boots of the Weeping Guardian",
	"Footfalls of the Eternal Night", "Boots of the Forsaken King", "Footfalls of the Infernal Beast",
	"Boots of the Lost Souls", "Footfalls of the Vengeful Shadows", "Boots of the Cursed Night",
	"Footfalls of the Eternal Scorn", "Boots of the Abyssal Void", "Footfalls of the Forsaken Echo",
	"Boots of the Infernal Storm", "Footfalls of the Darkened Path", "Boots of the Silent Guardian",
	"Footfalls of the Forsaken Watch", "Boots of the Ashen Guardian", "Footfalls of the Damned Flame",
	"Boots of the Eternal Guardian", "Footfalls of the Abyssal Embrace", "Boots of the Cursed King",
	"Footfalls of the Fallen Lord", "Boots of the Darkened King", "Footfalls of the Forsaken Fury",
	"Boots of the Eternal Woe", "Footfalls of the Abyssal Nightmare", "Boots of the Silent One",
	"Boots of the Damned Guardian", "Footfalls of the Forsaken Watcher", "Boots of the Darkened Souls",
	"Footfalls of the Vengeful Abyss", "Boots of the Eternal Wrath", "Footfalls of the Infernal Heart",
	"Boots of the Cursed Shadows", "Footfalls of the Forsaken Watch", "Boots of the Abyssal Keeper",
	"Footfalls of the Silent Tempest", "Boots of the Damned Echo", "Footfalls of the Forsaken Flame",
	"Boots of the Darkened Soul", "Footfalls of the Eternal Night", "Boots of the Abyssal Shadows",
	"Boots of the Infernal Watch", "Footfalls of the Weeping Souls", "Boots of the Forsaken King",
	"Footfalls of the Damned King", "Boots of the Silent Guardian", "Footfalls of the Eternal Flame",
	"Boots of the Abyssal Wrath", "Footfalls of the Cursed Fate", "Boots of the Forsaken Tempest",
	"Footfalls of the Darkened Heart", "Boots of the Eternal Guardian", "Footfalls of the Abyssal Fury",
	"Boots of the Infernal Nightmare", "Footfalls of the Lost Guardian", "Boots of the Forsaken Wastes",
	"Footfalls of the Weeping Abyss", "Boots of the Cursed Spirits", "Footfalls of the Eternal Ashes",
	"Boots of the Abyssal Flame", "Footfalls of the Forsaken Guardian", "Boots of the Damned Fury",
	"Footfalls of the Silent Flame", "Boots of the Infernal Embrace", "Footfalls of the Abyssal Shadow",
	"Boots of the Cursed Watcher", "Footfalls of the Eternal Night", "Boots of the Forsaken Watch",
	"Footfalls of the Darkened King", "Boots of the Vengeful King", "Footfalls of the Damned Fate",
	"Boots of the Silent Abyss", "Footfalls of the Eternal Guardian", "Boots of the Abyssal Wrath",
	"Footfalls of the Forsaken Flame", "Boots of the Darkened Guardian", "Footfalls of the Infernal Fire",
	"Boots of the Cursed Night", "Footfalls of the Eternal Scorn", "Boots of the Forsaken Wastes",
	"Footfalls of the Damned Flame", "Boots of the Silent Shadows", "Footfalls of the Abyssal Night",
	"Boots of the Vengeful Watch", "Footfalls of the Eternal Watcher", "Boots of the Forsaken Tempest",
	"Footfalls of the Infernal Guardian", "Boots of the Darkened Flame", "Footfalls of the Damned Woe",
	"Boots of the Silent Fury", "Footfalls of the Abyssal Guardian", "Boots of the Forsaken Night",
	"Footfalls of the Cursed Heart", "Boots of the Eternal Ashes", "Footfalls of the Darkened Soul",
	"Boots of the Lost King", "Footfalls of the Forsaken Guardian", "Boots of the Abyssal Fury",
	"Footfalls of the Infernal Watch", "Boots of the Cursed Spirit", "Footfalls of the Eternal Night",
	"Boots of the Forsaken Guardian", "Footfalls of the Darkened Fury", "Boots of the Silent Abyss",
	"Footfalls of the Damned Flame", "Boots of the Forsaken Woe", "Footfalls of the Abyssal Keeper",
	"Boots of the Eternal Guardian", "Footfalls of the Cursed Shadows", "Boots of the Lost Guardian",
	"Footfalls of the Silent Fury", "Boots of the Infernal Tyrant", "Footfalls of the Abyssal Reaver",
	"Boots of the Forsaken Shadow", "Footfalls of the Darkened Abyss", "Boots of the Eternal Night",
	"Footfalls of the Silent One", "Boots of the Infernal Flames", "Footfalls of the Forsaken Wastes",
	"Boots of the Abyssal Storm", "Footfalls of the Darkened Path", "Boots of the Eternal Wrath",
	"Footfalls of the Forsaken Fate", "Boots of the Damned Echo", "Footfalls of the Abyssal Watch",
	"Boots of the Silent Watcher", "Footfalls of the Cursed Abyss", "Boots of the Infernal Guardian",
	"Footfalls of the Forsaken Guardian",
}

var necklaces = []string{
	"Necklace of the Abyss", "Amulet of the Damned", "Necklace of the Forsaken", "Amulet of the Infernal",
	"Necklace of Eternal Wrath", "Amulet of the Blighted", "Necklace of Perdition", "Amulet of the Wretched",
	"Necklace of the Cursed", "Amulet of the Weeping Souls", "Necklace of the Lost", "Amulet of Malice",
	"Necklace of the Ashen", "Amulet of the Eternal Night", "Necklace of the Unholy", "Amulet of the Abyssal King",
	"Necklace of the Fallen", "Amulet of the Vengeful", "Necklace of the Darkened", "Amulet of Sinister Dreams",
	"Necklace of the Forsaken Guardian", "Amulet of Fiery Judgment", "Necklace of the Infernal Flames",
	"Amulet of the Silent Ones", "Necklace of the Eternal Shadows", "Amulet of the Damned Souls",
	"Necklace of the Forsaken Hope", "Amulet of the Eternal Woe", "Necklace of the Abyssal Fury",
	"Amulet of the Darkened Heart", "Necklace of the Cursed Flame", "Amulet of the Infernal Watch",
	"Necklace of the Silent Woe", "Amulet of the Forsaken Night", "Necklace of the Vengeful Fire",
	"Amulet of the Eternal Guardian", "Necklace of the Abyssal Reaver", "Amulet of the Fallen Angels",
	"Necklace of the Cursed Spirits", "Amulet of the Unrepentant", "Necklace of the Forsaken Tempest",
	"Amulet of the Ashen Wastes", "Necklace of Dark Despair", "Amulet of the Damned King",
	"Necklace of the Silent Fury", "Amulet of the Cursed Watcher", "Necklace of the Eternal Flame",
	"Amulet of the Forsaken Shadows", "Necklace of the Abyssal Watch", "Amulet of the Infernal Judge",
	"Necklace of the Darkened Fury", "Amulet of the Eternal Reaver", "Necklace of the Blighted Heart",
	"Amulet of the Silent Abyss", "Necklace of the Forsaken Woe", "Amulet of the Cursed Guardian",
	"Necklace of the Abyssal Guardian", "Amulet of the Fiery Abyss", "Necklace of the Weeping Guardian",
	"Amulet of the Eternal Night", "Necklace of the Forsaken King", "Amulet of the Infernal Beast",
	"Necklace of the Lost Souls", "Amulet of the Vengeful Shadows", "Necklace of the Cursed Night",
	"Amulet of the Eternal Scorn", "Necklace of the Abyssal Void", "Amulet of the Forsaken Echo",
	"Necklace of the Infernal Storm", "Amulet of the Darkened Path", "Necklace of the Silent Guardian",
	"Amulet of the Forsaken Watch", "Necklace of the Ashen Guardian", "Amulet of the Damned Flame",
	"Necklace of the Eternal Guardian", "Amulet of the Abyssal Embrace", "Necklace of the Cursed King",
	"Amulet of the Fallen Lord", "Necklace of the Darkened King", "Amulet of the Forsaken Fury",
	"Necklace of the Eternal Woe", "Amulet of the Abyssal Nightmare", "Necklace of the Silent One",
	"Amulet of the Damned Guardian", "Necklace of the Forsaken Watcher", "Amulet of the Darkened Souls",
	"Necklace of the Vengeful Abyss", "Amulet of the Eternal Wrath", "Necklace of the Infernal Heart",
	"Amulet of the Cursed Shadows", "Necklace of the Forsaken Watch", "Amulet of the Abyssal Keeper",
	"Necklace of the Silent Tempest", "Amulet of the Damned Echo", "Necklace of the Forsaken Flame",
	"Amulet of the Darkened Soul", "Necklace of the Eternal Night", "Amulet of the Abyssal Shadows",
	"Necklace of the Infernal Watch", "Amulet of the Weeping Souls", "Necklace of the Forsaken King",
	"Amulet of the Damned King", "Necklace of the Silent Guardian", "Amulet of the Eternal Flame",
	"Necklace of the Abyssal Wrath", "Amulet of the Cursed Fate", "Necklace of the Forsaken Tempest",
	"Amulet of the Darkened Heart", "Necklace of the Eternal Guardian", "Amulet of the Abyssal Fury",
	"Necklace of the Infernal Nightmare", "Amulet of the Lost Guardian", "Necklace of the Forsaken Wastes",
	"Amulet of the Weeping Abyss", "Necklace of the Cursed Spirits", "Amulet of the Eternal Ashes",
	"Necklace of the Abyssal Flame", "Amulet of the Forsaken Guardian", "Necklace of the Damned Fury",
	"Amulet of the Silent Flame", "Necklace of the Infernal Embrace", "Amulet of the Abyssal Shadow",
	"Necklace of the Cursed Watcher", "Amulet of the Eternal Night", "Necklace of the Forsaken Watch",
	"Amulet of the Darkened King", "Necklace of the Vengeful King", "Amulet of the Damned Fate",
	"Necklace of the Silent Abyss", "Amulet of the Eternal Guardian", "Necklace of the Abyssal Wrath",
	"Amulet of the Forsaken Flame", "Necklace of the Darkened Guardian", "Amulet of the Infernal Fire",
	"Necklace of the Cursed Night", "Amulet of the Eternal Scorn", "Necklace of the Forsaken Wastes",
	"Amulet of the Damned Flame", "Necklace of the Silent Shadows", "Amulet of the Abyssal Night",
	"Necklace of the Vengeful Watch", "Amulet of the Eternal Watcher", "Necklace of the Forsaken Tempest",
	"Amulet of the Infernal Guardian", "Necklace of the Darkened Flame", "Amulet of the Damned Woe",
	"Necklace of the Silent Fury", "Amulet of the Abyssal Guardian", "Necklace of the Forsaken Night",
	"Amulet of the Cursed Heart", "Necklace of the Eternal Ashes", "Amulet of the Darkened Soul",
	"Necklace of the Lost King", "Amulet of the Forsaken Guardian", "Necklace of the Abyssal Fury",
	"Amulet of the Infernal Watch", "Necklace of the Cursed Spirit", "Amulet of the Eternal Night",
	"Necklace of the Forsaken Guardian", "Amulet of the Darkened Fury", "Necklace of the Silent Abyss",
	"Amulet of the Damned Flame", "Necklace of the Forsaken Woe", "Amulet of the Abyssal Keeper",
	"Necklace of the Eternal Guardian", "Amulet of the Cursed Shadows", "Necklace of the Lost Guardian",
	"Amulet of the Silent Fury", "Necklace of the Infernal Tyrant", "Amulet of the Abyssal Reaver",
	"Necklace of the Forsaken Shadow", "Amulet of the Darkened Abyss", "Necklace of the Eternal Night",
	"Amulet of the Silent One", "Necklace of the Infernal Flames", "Amulet of the Forsaken Wastes",
	"Necklace of the Abyssal Storm", "Amulet of the Darkened Path", "Necklace of the Eternal Wrath",
	"Amulet of the Forsaken Fate", "Necklace of the Damned Echo", "Amulet of the Abyssal Watch",
	"Necklace of the Silent Watcher", "Amulet of the Cursed Abyss", "Necklace of the Infernal Guardian",
	"Amulet of the Forsaken Guardian",
}

var rings = []string{
	"Ring of the Abyss", "Band of the Damned", "Ring of the Forsaken", "Band of the Infernal",
	"Ring of Eternal Wrath", "Band of the Blighted", "Ring of Perdition", "Band of the Wretched",
	"Ring of the Cursed", "Band of the Weeping Souls", "Ring of the Lost", "Band of Malice",
	"Ring of the Ashen", "Band of the Eternal Night", "Ring of the Unholy", "Band of the Abyssal King",
	"Ring of the Fallen", "Band of the Vengeful", "Ring of the Darkened", "Band of Sinister Dreams",
	"Ring of the Forsaken Guardian", "Band of Fiery Judgment", "Ring of the Infernal Flames",
	"Band of the Silent Ones", "Ring of the Eternal Shadows", "Band of the Damned Souls",
	"Ring of the Forsaken Hope", "Band of the Eternal Woe", "Ring of the Abyssal Fury",
	"Band of the Darkened Heart", "Ring of the Cursed Flame", "Band of the Infernal Watch",
	"Ring of the Silent Woe", "Band of the Forsaken Night", "Ring of the Vengeful Fire",
	"Band of the Eternal Guardian", "Ring of the Abyssal Reaver", "Band of the Fallen Angels",
	"Ring of the Cursed Spirits", "Band of the Unrepentant", "Ring of the Forsaken Tempest",
	"Band of the Ashen Wastes", "Ring of Dark Despair", "Band of the Damned King",
	"Ring of the Silent Fury", "Band of the Cursed Watcher", "Ring of the Eternal Flame",
	"Band of the Forsaken Shadows", "Ring of the Abyssal Watch", "Band of the Infernal Judge",
	"Ring of the Darkened Fury", "Band of the Eternal Reaver", "Ring of the Blighted Heart",
	"Band of the Silent Abyss", "Ring of the Forsaken Woe", "Band of the Cursed Guardian",
	"Ring of the Abyssal Guardian", "Band of the Fiery Abyss", "Ring of the Weeping Guardian",
	"Band of the Eternal Night", "Ring of the Forsaken King", "Band of the Infernal Beast",
	"Ring of the Lost Souls", "Band of the Vengeful Shadows", "Ring of the Cursed Night",
	"Band of the Eternal Scorn", "Ring of the Abyssal Void", "Band of the Forsaken Echo",
	"Ring of the Infernal Storm", "Band of the Darkened Path", "Ring of the Silent Guardian",
	"Band of the Forsaken Watch", "Ring of the Ashen Guardian", "Band of the Damned Flame",
	"Ring of the Eternal Guardian", "Band of the Abyssal Embrace", "Ring of the Cursed King",
	"Band of the Fallen Lord", "Ring of the Darkened King", "Band of the Forsaken Fury",
	"Ring of the Eternal Woe", "Band of the Abyssal Nightmare", "Ring of the Silent One",
	"Band of the Damned Guardian", "Ring of the Forsaken Watcher", "Band of the Darkened Souls",
	"Ring of the Vengeful Abyss", "Band of the Eternal Wrath", "Ring of the Infernal Heart",
	"Band of the Cursed Shadows", "Ring of the Forsaken Watch", "Band of the Abyssal Keeper",
	"Ring of the Silent Tempest", "Band of the Damned Echo", "Ring of the Forsaken Flame",
	"Band of the Darkened Soul", "Ring of the Eternal Night", "Band of the Abyssal Shadows",
	"Ring of the Infernal Watch", "Band of the Weeping Souls", "Ring of the Forsaken King",
	"Band of the Damned King", "Ring of the Silent Guardian", "Band of the Eternal Flame",
	"Ring of the Abyssal Wrath", "Band of the Cursed Fate", "Ring of the Forsaken Tempest",
	"Band of the Darkened Heart", "Ring of the Eternal Guardian", "Band of the Abyssal Fury",
	"Ring of the Infernal Nightmare", "Band of the Lost Guardian", "Ring of the Forsaken Wastes",
	"Band of the Weeping Abyss", "Ring of the Cursed Spirits", "Band of the Eternal Ashes",
	"Ring of the Abyssal Flame", "Band of the Forsaken Guardian", "Ring of the Damned Fury",
	"Band of the Silent Flame", "Ring of the Infernal Embrace", "Band of the Abyssal Shadow",
	"Ring of the Cursed Watcher", "Band of the Eternal Night", "Ring of the Forsaken Watch",
	"Band of the Darkened King", "Ring of the Vengeful King", "Band of the Damned Fate",
	"Ring of the Silent Abyss", "Band of the Eternal Guardian", "Ring of the Abyssal Wrath",
	"Band of the Forsaken Flame", "Ring of the Darkened Guardian", "Band of the Infernal Fire",
	"Ring of the Cursed Night", "Band of the Eternal Scorn", "Ring of the Forsaken Wastes",
	"Band of the Damned Flame", "Ring of the Silent Shadows", "Band of the Abyssal Night",
	"Ring of the Vengeful Watch", "Band of the Eternal Watcher", "Ring of the Forsaken Tempest",
	"Band of the Infernal Guardian", "Ring of the Darkened Flame", "Band of the Damned Woe",
	"Ring of the Silent Fury", "Band of the Abyssal Guardian", "Ring of the Forsaken Night",
	"Band of the Cursed Heart", "Ring of the Eternal Ashes", "Band of the Darkened Soul",
	"Ring of the Lost King", "Band of the Forsaken Guardian", "Ring of the Abyssal Fury",
	"Band of the Infernal Watch", "Ring of the Cursed Spirit", "Band of the Eternal Night",
	"Ring of the Forsaken Guardian", "Band of the Darkened Fury", "Ring of the Silent Abyss",
	"Band of the Damned Flame", "Ring of the Forsaken Woe", "Band of the Abyssal Keeper",
	"Ring of the Eternal Guardian", "Band of the Cursed Shadows", "Ring of the Lost Guardian",
	"Band of the Silent Fury", "Ring of the Infernal Tyrant", "Band of the Abyssal Reaver",
	"Ring of the Forsaken Shadow", "Band of the Darkened Abyss", "Ring of the Eternal Night",
	"Band of the Silent One", "Ring of the Infernal Flames", "Band of the Forsaken Wastes",
	"Ring of the Abyssal Storm", "Band of the Darkened Path", "Ring of the Eternal Wrath",
	"Band of the Forsaken Fate", "Ring of the Damned Echo", "Band of the Abyssal Watch",
	"Ring of the Silent Watcher", "Band of the Cursed Abyss", "Ring of the Infernal Guardian",
	"Band of the Forsaken Guardian",
}

func GetItemName(i ItemClass) string {
	switch i {
	case Weapon:
		return weapons[rand.IntN(len(weapons))]
	case Head:
		return helmets[rand.IntN(len(helmets))]
	case Torso:
		return chestPlates[rand.IntN(len(chestPlates))]
	case Legs:
		return greaves[rand.IntN(len(greaves))]
	case Arms:
		return vambraces[rand.IntN(len(vambraces))]
	case Gloves:
		return gloves[rand.IntN(len(gloves))]
	case Boots:
		return boots[rand.IntN(len(boots))]
	case Necklace:
		return necklaces[rand.IntN(len(necklaces))]
	case Ring:
		return rings[rand.IntN(len(rings))]
	default:
		return ""
	}
}

var blessings = [][]string{
	// Circle 1: Limbo
	{
		"A glimmer of divine truth illuminates your mind.",
		"The wisdom of the ages grants you clarity of thought.",
		"The light of reason shines upon your path.",
		"You are blessed with the gift of philosophical insight.",
		"A spark of divine knowledge leads you closer to the truth.",
	},
	// Circle 2: Lust
	{
		"Your heart is purified by the flames of divine love.",
		"A veil of chastity shields you from temptation.",
		"You are granted the strength to resist the pull of lust.",
		"Divine grace fills your heart, driving away impure desires.",
		"The chains of passion fall away, leaving you free and clear.",
	},
	// Circle 3: Gluttony
	{
		"You are filled with the nourishment of the spirit, beyond earthly hunger.",
		"Divine grace grants you the strength to resist excess.",
		"You are blessed with the gift of temperance and moderation.",
		"Spiritual sustenance fills your soul, leaving no need for indulgence.",
		"A sense of divine satisfaction soothes your mortal cravings.",
	},
	// Circle 4: Greed
	{
		"You are blessed with the virtue of charity, freeing you from greed.",
		"The riches of Heaven fill your heart, leaving no need for earthly wealth.",
		"A sense of divine contentment releases you from material desires.",
		"You are gifted with spiritual abundance, beyond material riches.",
		"The blessings of generosity guide your actions, filling you with grace.",
	},
	// Circle 5: Wrath
	{
		"A wave of divine peace washes over your soul, quelling your anger.",
		"The light of forgiveness fills your heart, driving away wrath.",
		"You are blessed with the patience of the saints, unshaken by fury.",
		"Divine justice steadies your hand, guiding you away from violence.",
		"The serenity of Heaven calms your spirit, leaving no room for wrath.",
	},
	// Circle 6: Heresy
	{
		"You are blessed with unwavering faith, immune to heresy.",
		"The light of divine truth shields you from falsehood.",
		"A sense of spiritual clarity fills your mind, dispelling doubt.",
		"You are guided by the wisdom of the saints, immune to deception.",
		"The protection of grace guards you from the fires of heresy.",
	},
	// Circle 7: Violence
	{
		"You are shielded by divine mercy, safe from violence.",
		"The hand of God stays your wrath, guiding you to peace.",
		"A sense of divine protection surrounds you, keeping harm at bay.",
		"You are filled with the grace of peace, calming your violent urges.",
		"The strength of the saints steadies your hand, turning it from harm.",
	},
	// Circle 8: Fraud
	{
		"You are blessed with the gift of truth, immune to deception.",
		"The light of honesty guides your words and actions.",
		"You are granted the trust of others, blessed by divine truth.",
		"The grace of sincerity fills your heart, freeing you from falsehood.",
		"A sense of divine justice guards you from the snares of fraud.",
	},
	// Circle 9: Treachery
	{
		"You are blessed with the loyalty of Heaven, steadfast and true.",
		"The grace of divine loyalty fills your heart, shielding you from treachery.",
		"You are surrounded by the protection of faith, keeping betrayal at bay.",
		"The light of loyalty guides your every step, holding you fast in truth.",
		"The strength of divine grace shields you from the sin of treachery.",
	},
}

var curses = [][]string{
	// Circle 1: Limbo
	{
		"The shadow of doubt clouds your mind.",
		"You feel the ache of eternal separation from the divine.",
		"The absence of grace leaves you in spiritual desolation.",
		"Your soul yearns for the light but finds only darkness.",
		"You wander lost, searching for meaning that eludes you.",
	},
	// Circle 2: Lust
	{
		"The winds of lust toss your soul into unending desire.",
		"You are consumed by burning passion, never to be satisfied.",
		"Your heart is torn by the endless torment of unfulfilled longing.",
		"The curse of lust leaves you adrift, lost in desire.",
		"The fires of temptation burn within you, leaving you restless.",
	},
	// Circle 3: Gluttony
	{
		"The endless hunger gnaws at your soul, never to be sated.",
		"You are consumed by the need to indulge, but nothing satisfies.",
		"The curse of gluttony weighs upon you, sapping your strength.",
		"Your body weakens under the weight of overindulgence.",
		"The eternal feast turns to ashes in your mouth, leaving you starved.",
	},
	// Circle 4: Greed
	{
		"The weight of gold drags you down into the depths of greed.",
		"You are cursed to hoard endlessly, never finding satisfaction.",
		"The lust for wealth consumes you, leaving your soul empty.",
		"The curse of greed leaves you grasping for more, but finding nothing.",
		"The riches of the earth slip through your fingers, leaving you impoverished.",
	},
	// Circle 5: Wrath
	{
		"The flames of wrath burn within you, consuming your soul.",
		"You are cursed with uncontrollable rage, lashing out at all around you.",
		"The sin of anger clouds your judgment, leading you into destruction.",
		"The fury of Hell courses through your veins, driving you to violence.",
		"The curse of wrath leaves you blinded by hatred and fury.",
	},
	// Circle 6: Heresy
	{
		"You are cursed with doubt, questioning all that is holy.",
		"The flames of heresy burn within you, leading you astray.",
		"The sin of false belief clouds your mind, pulling you from the truth.",
		"You are tormented by the whispers of heresy, leading you into darkness.",
		"The fires of falsehood consume your spirit, leaving you lost.",
	},
	// Circle 7: Violence
	{
		"The blood of your enemies stains your hands, weighing down your soul.",
		"You are cursed with a thirst for violence, never to be quenched.",
		"The curse of brutality drives you to harm all who cross your path.",
		"The sin of violence consumes you, leaving you in a storm of destruction.",
		"Your soul is scarred by the harm you've done, and you find no peace.",
	},
	// Circle 8: Fraud
	{
		"The curse of lies entangles your soul, trapping you in deceit.",
		"You are cursed to deceive and be deceived, lost in falsehood.",
		"The sin of fraud poisons your tongue, leading you into betrayal.",
		"You are weighed down by the chains of your own deceptions.",
		"The curse of fraud leaves you untrustworthy and without allies.",
	},
	// Circle 9: Treachery
	{
		"The curse of betrayal gnaws at your soul, turning you against your allies.",
		"You are cursed to abandon all who trust you, left alone in the darkness.",
		"The sin of treachery binds you in chains of betrayal and lies.",
		"You are consumed by the icy grip of treachery, cut off from all light.",
		"The curse of treason leaves you isolated, forsaken by all.",
	},
}
